### ISSUE TITLE
Properties/options 

### ISSUE THREAD

**Issue by duckanator746** [Wurielle/izabela-desktop#1]
The options/properties cog doesn't work for me and 2 of my other friends. all using up to date windows 10. also isabella makes a ping noise when you alt+enter but doesn't output any audio when you press enter. It is as if enter doesnt cause it to commit.

**Comment by Wurielle** [comment]
Hey @duckanator746, thanks for letting me know about the issue, I recently made a rework of the whole app to implement features like auto-updates and windows installer and I might have broken some things along the way.. 
I noticed it works almost flawlessly on the machine I develop on but doesn't anymore on other machines. I'm going to look for a solution tonight when I get home and I'll let you know about it! 
I'm pretty sure the auto-updater works however so when it'll be fixed you'll probably get an update on system startup or after you restart the app.
