### ISSUE TITLE
Inability to put capital letters

### ISSUE THREAD

**Issue by Velocikitty** [Wurielle/izabela-desktop#10]
I'm sure this is just me being picky, but its a bit annoying having to go from typing like a normal person, to just all lower case letters to use it.

**Comment by Wurielle** [comment]
I probably can do something about that, will look into it in the future, thanks!

**Comment by Wurielle** [comment]
Fixed in [v0.12.0](https://github.com/Wurielle/izabela-desktop/releases/tag/v0.12.0).
