### ISSUE TITLE
Wierd Post 10 Windows Update Settings Issue

### ISSUE THREAD

**Issue by Velocikitty** [Wurielle/izabela-desktop#11]
Recently, I updated from 7 to 10, and now its not saving settings again.

Trying a reinstall, but this is gonna be such a minor one (Since its rare someone doesn't directly install the new OS instead of updating.)

EDIT - Reinstall fixed it, but just wanted to point it out, but this can just be classified as super rare/not important.

**Comment by Wurielle** [comment]
Fixed since [v0.6.0](https://github.com/Wurielle/izabela-desktop/releases/latest).
