### ISSUE TITLE
removing 2 letters

### ISSUE THREAD

**Issue by jasonekan** [Wurielle/izabela-desktop#16]
every time i press backspace it removes 2 letters instead of 1

**Comment by Wurielle** [comment]
There's a new version coming out soon that will resolve a lot of issues and introduce a lot of new features! I plan to release it in late July, if you can wait just a little longer that'd be awesome! c:

**Comment by Wurielle** [comment]
Also as long as the window is focused you can type any letters. I noticed it removes 2 letters only when the chat box is focused. Try typing outside the chat box (I know it's not very intuitive..) or use global mode by pressing `alt` + `enter` in the meantime. Let me know if that works better.

**Comment by Wurielle** [comment]
Fixed since [v0.6.0](https://github.com/Wurielle/izabela-desktop/releases/latest).
