### ISSUE TITLE
shotcut key

### ISSUE THREAD

**Issue by Abigao** [Wurielle/izabela-desktop#17]
alt + enter toggles some games in and out of windowed/full screen could you add a hotkey selector?

**Comment by Wurielle** [comment]
Hello @Abigao! Yes it's definitely a concern and something I plan to implement although it's one of the more challenging feature I'll have to work on so I cannot say when it will be implemented.

In the meantime however, you could try to launch the software as administrator as it is known to fix some issues concerning the software's priority within the system's shortcuts.
Let me know if it helps regarding your issue!

Also I just put up a dev board allowing you to track the development of all new features and/or bug fixes to give an idea of what to expect next: https://www.notion.so/wurielle/3b507a01858a4d5db28927c248a8dc47?v=c7c6bc64ff81406293916a7eb45fa484

Hope this helps!

**Comment by Wurielle** [comment]
Feature added in [v0.8.0](https://github.com/Wurielle/izabela-desktop/releases/tag/v0.8.0) (see #22).
