### ISSUE TITLE
Sound on start

### ISSUE THREAD

**Issue by matusli** [Wurielle/izabela-desktop#19]
Quick request for an option to be added:

(Software is amazing, thanks for the good work)
The issue with the program is i often talk over people, and it does get annoying for them. Would there be a chance to make the initial sound also be played out of the virtual audio cable to warn people of the incoming annoyance? 

Thanks in advance

**Comment by Wurielle** [comment]
Hello @matusli!

Thanks for reporting the issue! I'll try to see what I can do about it but it should definitely be possible. I'll add the feature to the dev board available [here](https://www.notion.so/3b507a01858a4d5db28927c248a8dc47?v=c7c6bc64ff81406293916a7eb45fa484).

Thanks a lot for helping the project!

**Comment by Wurielle** [comment]
Hello @matusli!

I added this feature in the [new build](https://github.com/Wurielle/izabela-desktop/releases/tag/v0.7.0).

It's available under the "Overlay" tab in the options.
![image](https://user-images.githubusercontent.com/15323067/73219504-99b82400-415c-11ea-8699-8cc5914a4cd4.png)

Thanks again for trying out the software!

**Comment by Wurielle** [comment]
Feature added in [v0.7.0](https://github.com/Wurielle/izabela-desktop/releases/tag/v0.7.0).
