### ISSUE TITLE
Feature request - Close Global Mode upon message sent (in sentence mode)

### ISSUE THREAD

**Issue by fa-dx** [Wurielle/izabela-desktop#2]
Hello, I was wondering if it would be possible to enable some kind of option that would close the Global Mode if you're in Sentence mode and have just pressed Enter for your last message. This would be useful if you're not typing constantly and can say what you need to say with 1 sentence so you don't want to Alt+Enter to close your Global Mode every time. Thank you!

**Comment by Wurielle** [comment]
Hi there, yes it is indeed possible! Before adding new options I need to refactor user settings a bit however. This feature shouldn't be too complicated to implement so I'll see what I can do about it during the coming updates! :)

**Comment by fa-dx** [comment]
Thanks a lot for getting back to me, much appreciated!

**Comment by Wurielle** [comment]
Oh sorry I didn't see the edit. Thank you so much for recommending it! I've been working on an update that I'm planning to release for the end of week. I'll go on the thread to let them know it's coming. Thanks again for your help towards everyone!
