### ISSUE TITLE
Overlay doesn't show up

### ISSUE THREAD

**Issue by CarolinaOne** [Wurielle/izabela-desktop#27]
The overlay doesn't show up, whether in game, or in Windows. It actually works as intended, you can hear the sound when it appears/disappears, and hear the voice if you type blindly and send. But nothing visual. Changing the key binding doesn't help.
Thank you!

**Comment by Wurielle** [comment]
Hello @CarolinaOne! Thanks for letting me know about the issue!

Did the overlay used to work before this happened (on a prior version of the software maybe)?
Are you running on Windows 7, 8 or 10?
Have you tried reinstalling it or installing it on another machine?

**Comment by CarolinaOne** [comment]
The overlay was working fine on the last version I used (0.5.7), and stopped working since I updated to 0.10.1 (though I understand it's a complete rework since a few versions). Running on Win7, reinstalled twice, no luck. No other machine I'm afraid.
(Not sure if relevant, the Overlay > Screen option shows a display with a weird number : "Display 2528732444 (Primary)")
I hope it helps!

**Comment by Wurielle** [comment]
If you have several displays connected can you try to select another display from the selection and see if it appears on that other display?

I'll try to see what I can do on my end this week, thanks for the details!

**Comment by Wurielle** [comment]
Hello again @CarolinaOne! 

I've been investigating the issue and it looks like on Windows 7 there are some window transparency issues. The click-through option from electron seems to prevent the overlay window from appearing so I added an option that let's you disable the click-through behavior. 

The only issue is that if you try to click through the overlay, you'll lose focus of the software you were using before toggling overlay mode. 
I tested it and usually it's not that common to try to click when typing in overlay mode anyway so it shouldn't be a major ux issue.

To fix your issue, go to settings under the "Overlay" tab and disable this option:
![image](https://user-images.githubusercontent.com/15323067/75624206-8c0a1a00-5bb2-11ea-9628-de8d007efd48.png)

**Comment by Wurielle** [comment]
On Windows 7 there's an issue related to the hardware where windows' transparency can appear to not be transparent and/or glitchy. Unfortunately this isn't something I can fix myself but it's something that can be fixed by the electron/chromium team so my best bet would be to keep updating these in the future and hope these issues get fixed.

I could probably develop a workaround for that issue but I'd like to confirm that it's happening with all Windows 7 users before jumping into it.

Please let me know if it solved your issue.

**Comment by CarolinaOne** [comment]
The Overlay Click-through option works fine, and solved the problem!
Thank a lot, great work!

**Comment by Wurielle** [comment]
Awesome! Thanks a lot for trying out the software and reporting the issue!
