### ISSUE TITLE
Say API is silent

### ISSUE THREAD

**Issue by ValSP** [Wurielle/izabela-desktop#29]
Hi there!

When the Say Text-to-Speech API is selected, Izabela won't transmit audio.

Some background: I'm using Windows 7. Responsive Voice seems to function perfectly when selected instead. I'm able to use my computer's installed voices on other TTS programs. They also playback fine in my OS's Speech settings.

Thanks for your time!

**Comment by Wurielle** [comment]
Hello @ValSP! Thanks for reporting the issue!

I didn't see you posted an issue about it and accidentally created a duplicate issue..
I shared some informations that could help me understand the problem [here](https://github.com/Wurielle/izabela-desktop/issues/30#issuecomment-590519523) and potentially fix this issue on your end.

Can you check out [this issue](https://github.com/Wurielle/izabela-desktop/issues/30) and tell me if this solves anything?

**Comment by ValSP** [comment]
Thanks for getting back so quickly.

I do have PowerShell installed, but it seems like it's only version 2.0 if that has any bearing.

**Comment by Wurielle** [comment]
Hello again @ValSP!

I've been investigating the issue and it looks like it's a known issue on Say.js (https://github.com/Marak/say.js/issues/55). I can't directly fix this on my end and it seems like the only workaround is to update PowerShell.

Here's a guide on how to update PowerShell: https://youtu.be/3jAH92mBbRk
Unfortunaly there's no easier option to fix this issue.. Sorry about that.
