### ISSUE TITLE
Voice randomly crashing (Responsive and SAY)

### ISSUE THREAD

**Issue by StaffTroll** [Wurielle/izabela-desktop#31]
One time it works flawlessly, one time it's just silent after clicking enter. I need to restart it to fix it. Both me and another person are both having this issue, she don't even use the Say API, so i guess it's widespread over the app completely.

Just posting this in case you are unaware of the issue.

**Comment by Wurielle** [comment]
Hello @StaffTroll! Thanks for reporting the issue!

I'll look into it soon, I know what could be causing the issue. Sorry for the inconvenience.

**Comment by Wurielle** [comment]
Should be fixed with [v0.10.3](https://github.com/Wurielle/izabela-desktop/releases/tag/v0.10.3).
