### ISSUE TITLE
Program messes with my keyboardlayout.

### ISSUE THREAD

**Issue by Myojine** [Wurielle/izabela-desktop#34]
I use a Nordic european keyboard which includes the letters å, ä and ö. It also has keys on different places, such as the ' sign. This makes it incredibly hard to use the english voices and trying to type things like "there's" since the ' comes out as a / sign and so it pronounces the word completely wrong.

Would it be possible to have Izabela not change your keyboards layout so that we can actually use all languages with one keyboard without having to re-wire our brains to use a different button to use a symbol or letter depending on which language we set the voice to?

**Comment by Wurielle** [comment]
Unfortunately I have to bind every keys for every possible keyboard layouts to make it work for everybody. I'm looking for solutions regarding this issue but the best thing I can do for now is to try to map keys for your current keyboard layout.

I'll try to see what I can do about it in the following days. Sorry for the inconvenience.

**Comment by StaffTroll** [comment]
I have the exact same issue as well, but i learn to just click different places, when using apostrophes, would also love if that got fixed

**Comment by Myojine** [comment]
Yeah, when writing in english you can (like StaffTroll said) learn to click different keys.

But when trying to type in swedish, norwegian and danish it's pretty much impossible because we can't type out å, ä, ö or ø properly so the voice says the words very wonky when trying to use "a" and "o" as supplementary letters. I guess one could try memorizing the positions for ¨ and atleast get ä and ö working. 😄

By the way, I noticed it's only in the overlay I can't use å ä or ö. In the Izabella window when it's opened as a window I don't have that problem. 😄

**Comment by Wurielle** [comment]
Fixed in [v0.12.0](https://github.com/Wurielle/izabela-desktop/releases/tag/v0.12.0).
