### ISSUE TITLE
Responsive Voice API "dot" bug

### ISSUE THREAD

**Issue by katawajojo** [Wurielle/izabela-desktop#39]
When entering any text, if there's a space after a period at the end of a sentence, Responsive Voice will end the phrase with "dot".

Also, if you place a period solo, it generates "dot dot".

It seems to be an use-case issue with periods and what's being sent to the Responsive Voice API.

**Comment by Wurielle** [comment]
Hello @katawajojo! Thanks for reporting the issue!

I am pretty sure it's a bug that was introduced with [this fix](https://github.com/Wurielle/izabela-desktop/issues/32#issuecomment-595956746). I should be able to fix in a following update! Thanks for letting me know!

**Comment by Wurielle** [comment]
Fixed in [v0.12.0](https://github.com/Wurielle/izabela-desktop/releases/tag/v0.12.0).
