### ISSUE TITLE
Chinese taiwan female and Japanese female voice don't work?

### ISSUE THREAD

**Issue by japaneseman** [Wurielle/izabela-desktop#4]
Hello, I can't hear anything when I select Chinese taiwan female or Japanese female.
Is it only me?

**Comment by Wurielle** [comment]
Hey there! 
Indeed, it seems there was some breaking changes with the Text-to-Speech API I'm using.
I just checked and managed to make the japanese voice work again but I need to check if all other voices are working correctly as well before pushing an update.
I'll try to have a look at it soon, thanks for reporting the issue!
