### ISSUE TITLE
Overlay only uses an American keyboard?

### ISSUE THREAD

**Issue by Addison14** [Wurielle/izabela-desktop#41]
Hello, when I was using this I noticed that it works fine full screened, but when I use the overlay it only uses the American keyboard? I was wondering if I'm just being silly and there is away to change this to a UK keyboard or not? 
Otherwise, I'd like to say thank you! As a mute person, it is very difficult to communicate with people and this has basically given me a voice!
Thank you :D

**Comment by Wurielle** [comment]
Hey @Addison14 ! Thanks a bunch for trying the software out! I'm so glad to know it's been helping you communicate despite your handicap and I'll make sure it keeps helping you just as much in the future! 😄 

Concerning the issue I've been looking at ways to seemlessly integrate the keyboard layout within the app without having to map every keys on my end which is what's causing the issue on your keyboard.
I may just have found a solution today so I'll try to work on that and release a fix next week if things go well! 

Thanks for your patience! ❤️

**Comment by Addison14** [comment]
Hello again! I didn't want to open another ticket for this as it is just a question about the upcoming changes!
Will the custom hotkey feature include the ability to stop the TTS at any point in the sentence? I've noticed when in voice chats with friends I have to commit to my message as soon as I press enter which means if someone else is using a TTS which acts the same way we end up in an awkward situation of us both talking over each other. Thanks!

**Comment by Wurielle** [comment]
I'll try to see if I can add that in in the next update otherwise I'll plan it for the next one! 😄

**Comment by Wurielle** [comment]
It's actually more complicated than I anticipated so I'll push an update with the fix to that issue first and work on that feature on another build 😭

**Comment by Addison14** [comment]
Thank you!

**Comment by Wurielle** [comment]
Should be fixed in [v0.12.0](https://github.com/Wurielle/izabela-desktop/releases/tag/v0.12.0)! Sorry if it took a while, I had to make sure it worked on several systems with several keyboard layouts but now it should be good to go!
