### ISSUE TITLE
no own bought voices?

### ISSUE THREAD

**Issue by Celinna1** [Wurielle/izabela-desktop#42]
hello, 
i bought an own voice from https://harposoftware.com/en/

but i cant activate it with your tool, this would be very very nice if you can implementation this

Edit: i take all back, found it under the other tab sry

**Comment by Wurielle** [comment]
Hi @Celinna1! Sorry for the late reply.. SAPI voices may be available under the Say API in the "Say" tab under "Text-to-Speech". If that's the case, select the voice you want to use and go to the "General" tab and select "Say" as the api you want to use.

I agree the process could be more straight forward but I'll be working on the UX soon to make everything simpler! 😄
