### ISSUE TITLE
Inability to use capitalization in overlay mode

### ISSUE THREAD

**Issue by kekvitirae** [Wurielle/izabela-desktop#43]
CAPSLOCK key only produces lower-case letters, and the Shift key + letter doesn't produce anything.

When typing in the program itself when it is not in overlay mode, everything works as normal.

**Comment by Wurielle** [comment]
Hey there! I just pushed an update that should fix the problem alongside some other keybinding issues with overlay mode. Make sure the app is updated to [v0.12.0](https://github.com/Wurielle/izabela-desktop/releases/tag/v0.12.0) and that should fix the issue for you! 😄

**Comment by kekvitirae** [comment]
Awesome! Just updated and the overlay mode works perfectly.
