### ISSUE TITLE
Updates every time I open it. 0.12

### ISSUE THREAD

**Issue by Mayruii** [Wurielle/izabela-desktop#46]
It still functions properly but every time I open it, it says "Requires update." Installs it then relaunches itself. I had auto updates disabled and it still happens.

**Comment by Wurielle** [comment]
Can you try to manually install the [latest version](https://github.com/Wurielle/izabela-desktop/releases/tag/latest) and see if it fixes the issue?

**Comment by Mayruii** [comment]
I cleared it completely from my computer and installed 0.12.1 and now the issue is resolved. I tried that with 0.12.0 and it persisted so not really sure what caused the issue at all.
