### ISSUE TITLE
Settings not being saved.

### ISSUE THREAD

**Issue by FlufflesTheDog** [Wurielle/izabela-desktop#5]
Settings seem to not persist through restarts of the application. 
Looking further into it, the user-settings.json file in appdata can be set to read-only before restarting and after customizing settings, which seems to provide a functional workaround. 

*This is also the first time I've used GitHub, so hopefully I'm doing this right.* 🤔

**Comment by Velocikitty** [comment]
Having the same issue with 7.

Even force running it as admin doesn't work.

**Comment by Wurielle** [comment]
It will be fixed in the next version. Sorry if this is taking long but I have to consider refactoring the code which is a long but worthwhile task.

I'll probably setup a trello or something very soon so you can be updated on what's being done.

Thank you for your understanding!

**Comment by Wurielle** [comment]
I published a release that should fix the issue. If you still encounter the issue, please check that you have version `0.5.7`. If it still persists, try deleting your `user-settings.json` file in `C:\Users\YourName\AppData\Roaming\Izabela`.
