### ISSUE TITLE
Unable to download Google Cloud TTS as an MP3

### ISSUE THREAD

**Issue by MisterVideosoEx** [Wurielle/izabela-desktop#72]
Every time I download the Google Cloud TTS, it says it has a file size of 0 and that it is unplayable. I also get an error code of 0xc00d36c4

**Comment by Wurielle** [comment]
Heya, thank you for sharing the issue with me! [I released an update yesterday](https://github.com/Wurielle/izabela-desktop/releases/tag/v0.14.2) that should fix the issue! Let me know if it works again for you 😄

**Comment by MisterVideosoEx** [comment]
It works, thanks!

(sorry for late reply)
