### ISSUE TITLE
new version 0.14.3 crackling sound

### ISSUE THREAD

**Issue by Celinna1** [Wurielle/izabela-desktop#73]
hello 
i have with this new version in discord crackling issues, ts3 works fine with it.

its "say" my own voice i bought.

**Comment by Celinna1** [comment]
ok found out its a discord issue not only izabella, when i set discord to high priority and only 1 core instead all 16 it works fine.

**Comment by Wurielle** [comment]
Hey there! I'm so sorry I didn't respond in time.. Thank you kindly for closing the issue after finding a solution ❤️
