### ISSUE TITLE
Closing overlay after sending a message

### ISSUE THREAD

**Issue by mykesZIP** [Wurielle/izabela-desktop#75]
Option to exit overlay after you're done typing would be great.
Instead of having to press _Esc_, it would make it automatically close when you hit _Enter_.

**Comment by Wurielle** [comment]
Hey there! Thank you for trying out the software!

There is such an option actually, I like to use it too! It's under Application / Overlay :smile:

![image](https://user-images.githubusercontent.com/15323067/152859828-b0905e49-c400-4845-802b-607341446d5b.png)

**Comment by mykesZIP** [comment]
Well this is embarrassing
I thought I checked through every option, but my dumbass somehow managed to miss it
Anyways thanks for the great software and constant updates 🤠

**Comment by Wurielle** [comment]
Thank you and no worries! I'm happy if the software is helping! 
Let me know if you notice any missing features or find anything unusual regardless 😄
