### ISSUE TITLE
Izabela not opening despite creating Process in Task Manager

### ISSUE THREAD

**Issue by Emilynyan** [Wurielle/izabela-desktop#76]
Title says it all pretty much, whenever I try to open Izabela nothing seems to happen but I can find 3 process for it in the Task Manager.

Re-installing it (even with the old 13.0 installer) didn't change the behaviour, but I'm also not aware of any other changes done to the System since it happened. Opening as Admin gives the same result as well..

**Comment by Wurielle** [comment]
Hey there! Sorry for the late response..

Can you try deleting the folder `C:\Users\USER\AppData\Roaming\Izabela` and see if reinstalling the latest version fixes it?
**Note: this will erase your user settings**

**Comment by Emilynyan** [comment]
No worries! 

Thought I tried that before but doing it again for safety seems to have done the trick. Thank you!

**Comment by Wurielle** [comment]
Awesome glad to hear! 😄
