### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by linthiel** [Wurielle/izabela-desktop#82]
Hello,

This isn't so much an issue but a feature request. I am currently trying to jerry-rig either windows speech recognition detection dictation or windows dictation (somehow, these are not the same thing ¯\_(ツ)_/¯, i.e., windows key plus H seems to be its own thing ) into Izabela and I am having an issue with windows dictation not recognizing that there is a text field in overlay mode maybe it needs to be tagged in some sort of way to be detected as a text field? Understandable if this is way too out of scope. The main issue with the former is it doesn't have any sort of key to activate speech recognition only works by clicking it or voice commands.

**Comment by Wurielle** [comment]
Hey there!

The input in overlay mode is not a native input and had to be implemented in a specific way to solve the unfocusable state of the overlay therefore it will never work with any third-party software that requires native input to write or read text.

Are you trying to use Izabela as speech-to-text-to-speech? If so this is a feature in Izabela v1 which is currently in alpha! If you'd like to try the feature feel free to add me on discord (Wuriko#0707) so I can help you set it up and explain to you how it works! 😊

**Comment by linthiel** [comment]
Hello,

Yeah, that's exactly what I'm trying to do so that is perfect. I was about ready to resort to using auto hotkey to automate that which would potentially be a nightmare to keep it from stealing focus lol. I would love to help you test it out.
