### ISSUE TITLE
ctrl + backspace to delete words, hotkey would be awesome

### ISSUE THREAD

**Issue by PyroghostX** [Wurielle/izabela-desktop#84]
ctrl + backspace to delete words, hotkey would be awesome

**Comment by Wurielle** [comment]
Hey there! If you don't mind, can you try to use the new v1 version available here: https://github.com/nature-heart-software/izabela ?
There's a better keyboard support there and ctrl + backspace should work just fine with that version 😄

**Comment by PyroghostX** [comment]
This is perfect! Thank you. using it now and its even better
